main/coaching/urls.py
from django.urls import path
from coaching import views

app_name = 'coaching'

urlpatterns = [
    path("", views.main_page, name="main"),
    path("posts", views.main_page, name="govno"),
    path("posts/<int:pk>/", views.PostDetailView.as_view(), name="posts"),
    path("form/", views.FormCreateView.as_view(), name="form"),
    path("requests/", views.RequestListView.as_view(), name="requests"),
    path("update_request/<int:pk>", views.UpdateFormView.as_view(), name="upd"),
    path("delete/<int:pk>", views.DeleteFormView.as_view(), name="del"),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("coaching.urls", namespace="coaching")),
    path('', include("users.urls", namespace="users")),
    path('__debug__/', include('debug_toolbar.urls')),
]

main/coaching/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from users.models import User
from django.utils.functional import cached_property



class ActiveManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(Active=True)
    
class ActiveFieldMixin(models.Model):
    active = models.BooleanField(name="Active", default=True)
    objects = models.Manager()
    active_objects = ActiveManager()
    class Meta:
        abstract = True

class TrainingExperience(models.Model):
    range = models.TextField()
    description = models.TextField()

    def __str__(self) -> str:
        return f"{self.description}"
class CoachingExperience(models.Model):
    range = models.TextField()
    description = models.TextField()

    def __str__(self) -> str:
        return f"{self.description}"
class SportTag(models.Model):
    name = models.TextField()
    description = models.TextField()

    def __str__(self) -> str:
        return f"{self.name}"

class SiteUser(models.Model):
    # email = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.TextField(null=True)
    age = models.IntegerField(null=True)
    experience = models.ForeignKey(to=TrainingExperience, on_delete=models.CASCADE, null=True)
    bio = models.TextField(null=True)

    class Meta:
        abstract = True



class Students(SiteUser):
    sport = models.ForeignKey(to=SportTag, on_delete=models.CASCADE, null=True)
    height = models.FloatField(null=True)
    weight = models.FloatField(null=True)

    def __str__(self) -> str:
        return f"{self.pk}"
    
# @receiver(post_save, sender=User)
# def create_profile(sender, instance, **kwargs):
#     print("Сработал обработчик сигнала.")
#     if not Students.objects.filter(email=instance).exists():
#         Students.objects.create(email=instance)

class Coaches(SiteUser):
    sport = models.ForeignKey(to=SportTag, on_delete=models.CASCADE, null=True)
    coaching_experience = models.ForeignKey(to=CoachingExperience, on_delete=models.CASCADE, null=True)

    def __str__(self) -> str:
        return f"{self.name}"      

class ClientRequest(ActiveFieldMixin):
    name = models.TextField()
    age = models.IntegerField()
    sport = models.ForeignKey(to=SportTag, on_delete=models.CASCADE)
    experience = models.ForeignKey(to=TrainingExperience, on_delete=models.CASCADE)
    request = models.TextField()

    @cached_property
    def get_all_requests(self):
        a = ClientRequest.objects.all()
        return a

    def __str__(self) -> str:
        return f"{self.pk}"

class CoachPosts(ActiveFieldMixin):
    sport = models.ForeignKey(to=SportTag, on_delete=models.CASCADE)
    #coach = models.ForeignKey(to=Coaches, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self) -> str:
        return f"{self.pk}"
    

main/coaching/forms.py
from django import forms
from django.forms import widgets
from .models import TrainingExperience, SportTag, ClientRequest

# class ClientForm(forms.Form):
#     name = forms.CharField(label="Имя")
#     age = forms.IntegerField(label="Возраст")
#     sport = forms.ModelChoiceField(label="Вид спорта", queryset=SportTag.objects.all(), empty_label="Категория не выбрана!")
#     experience = forms.ModelChoiceField(label="Опыт", queryset=TrainingExperience.objects.all(), empty_label="Категория не выбрана!")
#     request = forms.CharField(label="Описание", widget=forms.Textarea(attrs={"cols":60, "rows": 7}))

class ClientForm(forms.ModelForm):
    #name = forms.CharField(label="Имя")
    #birth_date = forms.DateField(label="Дата рождения", widget=forms.NumberInput(attrs={"class": "form-control", "style":"width:400px"}))
    sport = forms.ModelChoiceField(label="Вид спорта", queryset=SportTag.objects.all(), empty_label="Категория не выбрана!",  widget=forms.Select(attrs={"class": "form-control", "style":"width:400px"}))
    experience = forms.ModelChoiceField(label="Опыт", queryset=TrainingExperience.objects.all(), empty_label="Категория не выбрана!", widget=forms.Select(attrs={"class": "form-control", "style":"width:400px"}))
    request = forms.CharField(label="Описание", widget=forms.Textarea(attrs={"cols":60, "rows": 5, "class":"form-control", "placeholder": "Подробно опишите ваш запрос..."}))
    class Meta:
        model = ClientRequest
        fields = "__all__"

        labels = {
           "name": "Имя"
        }
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "Ваше ФИО", "class": "form-control", "style":"width:400px"}),
            "experience": widgets.ChoiceWidget(attrs={"class":"form-control"})
        }

main/coaching/views.py
from urllib import request
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, get_list_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, FormView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import ClientForm
from .models import SportTag, ClientRequest, CoachPosts, Students, Coaches
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

def main_page(request):
    title = "pasasi"
    return render(request, "coaching/index.html", context={"title":title})

class MyContextMixin(ContextMixin):
    def get_context_data(self, **kwargs: any) -> dict[str, any]:
        context = super().get_context_data(**kwargs)
        context['coach']= 'Соколов Алексей'
        return context

class RequestListView(ListView, MyContextMixin):
    model = ClientRequest.active_objects.all()
    reqs = ClientRequest.active_objects.select_related("sport").all()
    def get_queryset(self):
        return self.model
    paginate_by = 2

    def get_context_data(self, **kwargs: any) -> dict[str, any]:
        context = super().get_context_data(**kwargs)
        context['title'] = "pasasi"
        context['model'] = ClientRequest
        return context
    template_name = "coaching/requests.html"

class PostDetailView(UserPassesTestMixin, DetailView):
    model = ClientRequest
    # requests = ClientRequest.get_all_requests()
    # print(requests)
    
    template_name = "coaching/posts.html"

    # def test_func(self):
    #     if self.request.user.is_superuser:
    #         return super().test_func()
    #     else:
    #         return False

class FormCreateView(LoginRequiredMixin, CreateView):
    model = ClientRequest
    form_class = ClientForm
    success_url = reverse_lazy("coaching:requests")
    template_name = "coaching/contact.html"

    
        

class UpdateFormView(UpdateView):
    model = ClientRequest
    form_class = ClientForm
    success_url = reverse_lazy("coaching:requests")
    template_name = "coaching/update_req.html"

class DeleteFormView(DeleteView):
    model = ClientRequest
    success_url = reverse_lazy("coaching:requests")
    template_name = "coaching/delete_req.html"

main/coaching/templates/coaching/about.html
{% extends "base.html" %}

{% block header %}

<header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>About Me</h1>
                    <span class="subheading">This is what I do.</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
            </div>
            
            <table>
                <thead>
                    <tr>
                        <th colspan="2">Виды спорта</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in db %}
                    <tr>
                        <td>{{obj.name}}</td>
                        <td>{{obj.description}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
        </div>
    </div>
</main>
{% endblock %}

main/coaching/templates/coaching/contact.html
{% extends "base.html" %}

{% block header %}
<header class="masthead" style="background-image: url('/static/assets/img/contact-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Contact Me</h1>
                    <span class="subheading">Have questions? I have answers.</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                <div class="my-5">
                    
                    <form method="post" id="contactForm" data-sb-form-api-token="API_TOKEN">
                        {% csrf_token %}
                        {{form.as_p}}
                        
              
                                                    
                        <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

main/coaching/templates/coaching/delete_req.html
{% extends "base.html" %}

{% block header %}
<header class="masthead" style="background-image: url('/static/assets/img/contact-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Удаление заявки</h1>
                    <span class="subheading">Подтвердите удаление</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>После подтвреждения действие будет невозможно отменить</p>
                <div class="my-5">
                    
                    <form method="post" id="contactForm" data-sb-form-api-token="API_TOKEN">
                        {% csrf_token %}
                        
                        
              
                                                    
                        <div class="d-flex justify-content-center mb-4"><button class="btn btn-danger text-uppercase justify-content-center" id="submitButton" type="submit">Подтвердить</button></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

main/coaching/templates/coaching/govno.html
{% extends "base.html" %}

{% block header %}
<header class="masthead" style="background-image: url('/static/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>Man must explore, and this is exploration at its greatest</h1>
                    <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                    <span class="meta">
                        Posted by
                        <a href="#!">Start Bootstrap</a>
                        on August 24, 2022
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>
                <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>
                <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>
                <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>
                <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>
                <h2 class="section-heading">The Final Frontier</h2>
                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>
                <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>
                <h2 class="section-heading">Reaching for the Stars</h2>
                <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>
                <a href="#!"><img class="img-fluid" src="assets/img/post-sample-image.jpg" alt="..." /></a>
                <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
                <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>
                <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>
                <p>
                    Placeholder text by
                    <a href="http://spaceipsum.com/">Space Ipsum</a>
                    &middot; Images by
                    <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>
                </p>
            </div>
        </div>
    </div>
</article>
{% endblock %}

main/coaching/templates/coaching/index.html
{% extends "base.html" %}

{% block header %}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title">Man must explore, and this is exploration at its greatest</h2>
                    <h3 class="post-subtitle">Problems look mighty small from 150 miles up</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on September 24, 2022
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html"><h2 class="post-title">I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.</h2></a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on September 18, 2022
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title">Science has not yet mastered prophecy</h2>
                    <h3 class="post-subtitle">We predict too much for the next year and yet far too little for the next ten.</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on August 24, 2022
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title">Failure is not an option</h2>
                    <h3 class="post-subtitle">Many say exploration is part of our destiny, but it’s actually our duty to future generations.</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on July 8, 2022
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
        </div>
    </div>
</div>
{% endblock %}

main/coaching/templates/coaching/post.html
{% extends "base.html" %}

{% block header %}
<header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>Man must explore, and this is exploration at its greatest</h1>
                    <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                    <span class="meta">
                        Posted by
                        <a href="#!">Start Bootstrap</a>
                        on August 24, 2022
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>
                <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>
                <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>
                <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>
                <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>
                <h2 class="section-heading">The Final Frontier</h2>
                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>
                <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>
                <h2 class="section-heading">Reaching for the Stars</h2>
                <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>
                <a href="#!"><img class="img-fluid" src="assets/img/post-sample-image.jpg" alt="..." /></a>
                <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
                <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>
                <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>
                <p>
                    Placeholder text by
                    <a href="http://spaceipsum.com/">Space Ipsum</a>
                    &middot; Images by
                    <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>
                </p>
            </div>
        </div>
    </div>
</article>
{% endblock %}

main/coaching/templates/coaching/posts.html
{% extends "base.html" %}

{% block header %}

<header class="masthead" style="background-image: url('/static/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>About Me</h1>
                    <span class="subheading">This is what I do.</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <p >Виды спорта</p>
            <div class="col-md-10 col-lg-8 col-xl-2">
                <p>{{object.sport}}</p>
                <p>{{object.name}}</p>
                <p>{{object.request}}</p>
            </div>
            
            <table>
                <thead>
                    <tr>
                        <th colspan="2">Виды спорта</th>
                    </tr>
                </thead>
                <tbody>
                    
                    <tr>
                        <td>{{object.sport}}</td>
                        <td>{{object.name}}</td>
                        <td>{{object.request}}</td>
                    </tr>
                    
                </tbody>
            </table>
            <div class="d-flex justify-content-center mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'coaching:del' pk=object.pk %}">Удалить заявку</a></div>
        </div>
    </div>
</main>
{% endblock %}

main/coaching/templates/coaching/requests.html
{% extends "base.html" %}

{%load tags %}

{% block header %}
<header class="masthead" style="background-image: url('/static/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>Заявки</h1>
                    <h2 class="subheading">{{coach}}</h2>
                    <span class="meta">
                        
                        <a href="/#!">govno</a>
                        
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            {% for item in reqs %}
            <div class="post-preview">
                <a href="{% url 'coaching:posts' pk=item.pk %}">
                    <h2 class="post-title">{{item.name}}</h2>
                    <h3 class="post-subtitle">{{item.request}}</h3>
                </a>
                <p class="post-meta">
                    {{item.experience}}
                    <a href="#!">{{item.sport}}</a>
                    <a href="{% url 'coaching:upd' pk=item.pk %}">Изменить данные</a>
                </p>
            </div>
            {% endfor %}
            <div style="display: flex; width: 200px; border: 2px solid black; justify-content: space-evenly;">
                {% if page_obj.has_previous %}
                <a href="?page=1">First </a>
                {% endif %}
                {% for p in paginator.page_range %}
                {% if p == page_obj.previous_page_number or p == page_obj.next_page_number %}

                <a href="?page={{p}}">{{p}}</a>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <a href="?page={{paginator.num_pages}}">Last</a>
                
                {% endif %}
            </div>
            
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
        </div>
    </div>
</div>
{% endblock %}

main/coaching/templates/coaching/update_req.html
{% extends "base.html" %}

{% block header %}
<header class="masthead" style="background-image: url('/static/assets/img/contact-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Отредактировать заявку</h1>
                    <span class="subheading">Введите необходимые изменения</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                <div class="my-5">
                    
                    <form method="post" id="contactForm" data-sb-form-api-token="API_TOKEN">
                        {% csrf_token %}
                        {{form.as_p}}
                        
              
                                                    
                        <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}